[project]
name = "cppp"
version = "0.1.0"
description = "Continuous psychophysics for proprioception"
authors = [
    {name = "D. Straub",email = "ds2181@cam.ac.uk"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lqg (==0.2.11)",
    "matplotlib (>=3.10.3,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "arviz (>=0.22.0,<0.23.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
